version: '3.7'

services:
  nginx:
    env_file:
      - .env
      - .build_env

  host:
    build:
      context: ./projects/host
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env

  db:
    env_file:
      - .env
      - .build_env

  adminer:
    env_file:
      - .env
      - .build_env
