version: '3.3'

services:
  nginx:
    container_name: demo_development_nginx
    env_file:
      - .env
      - .development_env
      - .development_secrets

  host:
    container_name: demo_development_host
    build:
      context: ./projects/host
      dockerfile: Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-100}
    env_file:
      - .env
      - .development_env
      - .development_secrets
    labels:
      ports: "3000"
    volumes:
    - ./projects/host:/app
    - host_assets:/assets
    - host_bundle:/bundle
    - host_node_modules:/node_modules
    - host_log:/app/log
    - host_tmp:/app/tmp

  db:
    container_name: demo_development_db
    env_file:
      - .env
      - .development_env
      - .development_secrets
    volumes:
    - development_postgres_data:/data

  adminer:
    container_name: demo_development_adminer
    env_file:
      - .env
      - .development_env
      - .development_secrets

volumes:
  development_postgres_data:
  host_assets:
  host_bundle:
  host_node_modules:
  host_log:
  host_tmp:
