version: '3.3'

services:
  host:
    build:
      dockerfile: Dockerfile.build
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
    entrypoint: ["sleep", "infinity"]

  db:
    environment:
      POSTGRES_DB: production
