services:
  nginx:
    container_name: demo_peoduction_nginx
    env_file:
      - .env
      - .production_env
      - .production_secrets

  host:
    container_name: demo_production_host
    image: docker.ikari.fi/demo_build_host:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets

  db:
    container_name: demo_production_db
    env_file:
      - .env
      - .production_env
      - .production_secrets

  adminer:
    container_name: demo_production_adminer
    env_file:
      - .env
      - .production_env
      - .production_secrets
