version: '3.3'

services:
  nginx:
    env_file:
      - .env
      - .build_env

  host:
    build:
      context: ./projects/host
      dockerfile: Dockerfile.build
    env_file:
      - .env
      - .build_env
    secrets:
      - HOST_MASTER_KEY

  db:
    env_file:
      - .env
      - .build_env

  adminer:
    env_file:
      - .env
      - .build_env
