version: '3.8'

services:
  nginx:
    env_file:
      - .env
      - .build_env

  host:
    build:
      context: ./projects/host
      dockerfile: Dockerfile.build
      args:
        APP_PATH: /ui
    env_file:
      - .env
      - .build_env

  db:
    env_file:
      - .env
      - .build_env

  adminer:
    env_file:
      - .env
      - .build_env
