services:
  nginx:
    container_name: demo_production_nginx
    env_file:
      - .env
      - .production_env
      - .production_secrets

  host:
    container_name: demo_production_host
    image: docker.ikari.fi/demo_build_host:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
      - .production_secrets
    volumes:
      - ./host-service/docker/webapp.conf:/etc/nginx/sites-enabled/webapp.conf
      - ./host-service/docker/webapp_env.conf:/etc/nginx/main.d/webapp_env.conf

  db:
    container_name: demo_production_db
    env_file:
      - .env
      - .production_env
      - .production_secrets

  adminer:
    container_name: demo_production_adminer
    env_file:
      - .env
      - .production_env
      - .production_secrets
