version: '3.3'

services:
  nginx:
    env_file:
      - .env
      - .development_env

  host:
    build:
      context: ./projects/host
      dockerfile: Dockerfile
      args:
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_GID: ${DOCKER_GID}
    env_file:
      - .env
      - .development_env
    secrets:
      - HOST_MASTER_KEY
    labels:
      ports: "3000"
    volumes:
      - ./projects/host:/app
      - host_assets:/app/public/assets
      - host_bundle:/bundle
      - host_node_modules:/node_modules
      - host_tmp:/app/tmp
    tmpfs:
      - /pids:mode=7777,size=1k,uid=${DOCKER_UID},gid=${DOCKER_GID}

  db:
    env_file:
      - .env
      - .development_env
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  adminer:
   env_file:
      - .env
      - .development_env

volumes:
  host_assets:
  host_bundle:
  host_node_modules:
  host_tmp:

secrets:
  POSTGRES_PASSWORD:
    file: .development_secrets/POSTGRES_PASSWORD
  POSTGRES_USER:
    file: .development_secrets/POSTGRES_USER
  HOST_MASTER_KEY:
    file: .development_secrets/HOST_MASTER_KEY
