version: '3.7'

services:
  nginx:
    env_file:
      - .env
      - .production_env
    restart: unless-stopped

  host:
    image: ${DOCKER_REGISTRY_URL}/${BUILD_NAME}_build_host:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
    environment:
      CONTAINER_VERSION: ${BUILD_TAG}
    secrets:
      - HOST_MASTER_KEY
    volumes:
      - host_log:/home/app/webapp/log
      - host_tmp:/home/app/webapp/tmp
    restart: unless-stopped
    tmpfs:
      - /pids:mode=7777,size=1k,uid=app,gid=app

  db:
    env_file:
      - .env
      - .production_env
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    restart: unless-stopped

  adminer:
    env_file:
      - .env
      - .production_env

secrets:
  POSTGRES_PASSWORD:
    file: .production_secrets/POSTGRES_PASSWORD
  POSTGRES_USER:
    file: .production_secrets/POSTGRES_USER
  HOST_MASTER_KEY:
    file: .production_secrets/HOST_MASTER_KEY

volumes:
  host_log:
  host_tmp:
