version: '3.3'

services:
  nginx:
    image: nginx:1.19.9
    container_name: nginx
    env_file:
      - .env
    volumes:
     - ./nginx-service/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    ports:
      - "127.0.0.1:${NGINX_PORT}:8080"
    command: ['nginx', '-g', 'daemon off;']

  host:
    container_name: host
    env_file:
      - .env
    environment:
      SERVER_MODE: $SERVER_MODE
    logging:
      options:
        max-size: "1m"
        max-file: "2"
    working_dir: /app
    volumes:
    - host_log:/app/log
    - host_tmp:/app/tmp
    networks:
      - backend
    depends_on:
      - db
      - nginx

  db:
    image: postgres:13.2
    container_name: db
    env_file:
      - .env
    environment:
      PGDATA: /data/db
    logging:
      options:
        max-size: "1m"
        max-file: "2"
    volumes:
    - postgres_data:/data
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    profiles: ["dev"]
    restart: always
    logging:
      options:
        max-size: "1m"
        max-file: "2"
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  host_log:
  host_tmp:
