version: '3.3'

services:
  host:
    build:
      context: ./projects/host
      dockerfile: Dockerfile.build
      args:
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-100}
    environment:
      RAILS_SERVE_STATIC_FILES: "true"
    entrypoint: ["sleep", "infinity"]

  db:
    environment:
      POSTGRES_DB: production
