version: '3.3'

services:
  host:
    build:
      context: ./projects/host
      dockerfile: Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-100}
    ports:
      - "3000"
    volumes:
    volumes:
    - ./projects/host:/app
    - host_assets:/assets
    - host_bundle:/bundle
    - host_node_modules:/node_modules
    ports:
      - "3000"

  db:
    ports:
      - "5432"

  adminer:
    ports:
      - "8080"

volumes:
  host_assets:
  host_bundle:
  host_node_modules:
