version: '3.3'

services:
  nginx:
    container_name: demo_development_nginx
    env_file:
      - .env
      - .development_env

  host:
    container_name: demo_development_host
    build:
      context: ./projects/host
      dockerfile: Dockerfile
      args:
        - DOCKER_UID=${DOCKER_UID:-1000}
        - DOCKER_GID=${DOCKER_GID:-100}
    env_file:
      - .env
      - .development_env
    secrets:
      - HOST_MASTER_KEY
    labels:
      ports: "3000"
    volumes:
    - ./projects/host:/app
    - host_assets:/assets
    - host_bundle:/bundle
    - host_node_modules:/node_modules

  db:
    container_name: demo_development_db
    env_file:
      - .env
      - .development_env
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

  adminer:
    container_name: demo_development_adminer
    env_file:
      - .env
      - .development_env

volumes:
  host_assets:
  host_bundle:
  host_node_modules:

secrets:
  POSTGRES_PASSWORD:
    file: .development_secrets/POSTGRES_PASSWORD
  POSTGRES_USER:
    file: .development_secrets/POSTGRES_USER
  HOST_MASTER_KEY:
    file: .development_secrets/HOST_MASTER_KEY
