services:
  nginx:
    env_file:
      - .env
      - .production_env
    restart: always

  host:
    image: ${DOCKER_REGISTRY_URL}/${BUILD_NAME}_build_host:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
    environment:
      CONTAINER_VERSION: ${BUILD_TAG}
    secrets:
      - HOST_MASTER_KEY
    volumes:
      - host_log:/home/app/webapp/log
      - host_tmp:/home/app/webapp/tmp
      - ./host-service/docker/webapp.conf:/etc/nginx/sites-enabled/webapp.conf
      - ./host-service/docker/webapp_env.conf:/etc/nginx/main.d/webapp_env.conf
    restart: always

  db:
    env_file:
      - .env
      - .production_env
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    restart: always

  adminer:
    env_file:
      - .env
      - .production_env

secrets:
  POSTGRES_PASSWORD:
    file: .production_secrets/POSTGRES_PASSWORD
  POSTGRES_USER:
    file: .production_secrets/POSTGRES_USER
  HOST_MASTER_KEY:
    file: .production_secrets/HOST_MASTER_KEY

volumes:
  host_log:
  host_tmp:
